<a href="https://colab.research.google.com/github/danielrodriguez007/Data_Analysis/blob/main/Movie_Rating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [4]:
movies = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/movies.dat', delimiter = '::')
movies.head()

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

,0000008,Edison Kinetoscopic Record of a Sneeze (1894),Documentary|Short
0,10,La sortie des usines Lumière (1895),Documentary|Short
1,12,The Arrival of a Train (1896),Documentary|Short
2,25,The Oxford and Cambridge University Boat Race ...,NaN
3,91,Le manoir du diable (1896),Short|Horror
4,131,Une nuit terrible (1896),Short|Comedy|Horror

In [5]:
movies.columns = ["ID", "Title","Genre"]
movies.head()

    ID                                              Title                Genre
0   10                La sortie des usines Lumière (1895)    Documentary|Short
1   12                      The Arrival of a Train (1896)    Documentary|Short
2   25  The Oxford and Cambridge University Boat Race ...                  NaN
3   91                         Le manoir du diable (1896)         Short|Horror
4  131                           Une nuit terrible (1896)  Short|Comedy|Horror

In [7]:
ratings = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ratings.dat', delimiter='::')
ratings.head()

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)

   1  0114508  8  1381006850
0  2   499549  9  1376753198
1  2  1305591  8  1376742507
2  2  1428538  1  1371307089
3  3    75314  1  1595468524
4  3   102926  9  1590148016

In [8]:
ratings.columns = ["User", "ID", "Ratings", "Timestamp"]
ratings.head()

   User       ID  Ratings   Timestamp
0     2   499549        9  1376753198
1     2  1305591        8  1376742507
2     2  1428538        1  1371307089
3     3    75314        1  1595468524
4     3   102926        9  1590148016

In [9]:
data = pd.merge(movies, ratings, on=["ID", "ID"])
data.head()

,ID,Title,Genre,User,Ratings,Timestamp
0,10,La sortie des usines Lumière (1895),Documentary|Short,70577,10,1412878553
1,12,The Arrival of a Train (1896),Documentary|Short,69535,10,1439248579
2,25,The Oxford and Cambridge University Boat Race ...,NaN,37628,8,1488189899
3,91,Le manoir du diable (1896),Short|Horror,5814,6,1385233195
4,91,Le manoir du diable (1896),Short|Horror,37239,5,1532347349

In [11]:
ratings = data['Ratings'].value_counts()
numbers = ratings.index
quantity = ratings.values
import plotly.express as px 
fig = px.pie(data, values=quantity, names=numbers)
fig.show()

In [12]:
data2= data.query("Ratings==10")
print(data2["Title"].value_counts().head(10))

Joker (2019)                       1479
Interstellar (2014)                1386
1917 (2019)                         820
Avengers: Endgame (2019)            812
The Shawshank Redemption (1994)     707
Gravity (2013)                      653
The Wolf of Wall Street (2013)      581
Hacksaw Ridge (2016)                570
Avengers: Infinity War (2018)       535
La La Land (2016)                   510
Name: Title, dtype: int64